name: WorldCivScoreboards
main: com.worldciv.the60th.MainTorch
version: 1.0
commands:
  toggle:
    description:
    usage:
  toggleblind:
    description:
    usage:
permissions:
  worldciv.toggleblind:
    description:
  worldciv.cmds:
    description:
