name: OfficialWorldCiv
main: com.worldciv.devteam.main
version: 1.0
commands:
  toggle:
    description:
    usage:
  toggleblind:
    description:
    usage:
  news:
    description:
    usage:
permissions:
  worldciv.toggleblind:
    description:
  worldciv.cmds:
    description:
  worldciv.news:
    description:
